- set_fact: SLURM_CONF="/usr/local/etc/slurm.conf" SLURM_SERVICE="slurmctld"
  when: ansible_os_family == "Debian"

- set_fact: SLURM_CONF="/etc/slurm/slurm.conf" SLURM_SERVICE="slurm"
  when: ansible_os_family == "RedHat"

- name: Check cons_res enabled
  lineinfile:
    dest: "{{ SLURM_CONF }}"
    line: "SelectType=select/cons_res"
    state: present
  check_mode: yes
  register: cons_res_enabled

- lineinfile: dest={{SLURM_CONF}} regexp='NodeName=' line='NodeName={{vnode_prefix}}[1-{{ec3_max_instances|int}}] CPUs={{ wn_cpus }} State=UNKNOWN'
  when: cons_res_enabled is not changed

- lineinfile: dest={{SLURM_CONF}} regexp='NodeName=' line='NodeName={{vnode_prefix}}[1-{{ec3_max_instances|int}}] CPUs=1 State=UNKNOWN'
  when: cons_res_enabled is changed

- lineinfile: dest={{SLURM_CONF}} regexp='PartitionName=' line='PartitionName=debug Nodes={{vnode_prefix}}[1-{{ec3_max_instances|int}}] Default=YES MaxTime=INFINITE State=UP'

# start SLURM daemon
- name: Start SLURM service
  become: true
  become_user: slurm
  command: slurmctld

- name: Wait Slurm daemon to be up
  wait_for:
    port: 6817

- shell: scontrol reconfig

- ini_file: dest=/etc/clues2/clues2.cfg section=general option=LRMS_CLASS value=cluesplugins.slurm
  notify: restart cluesd
- copy: src=/etc/clues2/conf.d/plugin-slurm.cfg-example dest=/etc/clues2/conf.d/plugin-slurm.cfg force=no
  notify: restart cluesd
- ini_file: dest=/etc/clues2/conf.d/plugin-slurm.cfg section=SLURM option=SLURM_SERVER value=slurmserver
  notify: restart cluesd
- ini_file: dest=/etc/clues2/conf.d/plugin-slurm.cfg section=SLURM option=SLURM_PARTITION_COMMAND value="{{item}} -o show partitions"
  with_first_found:
   - /usr/bin/scontrol
   - /usr/local/bin/scontrol
  notify: restart cluesd
- ini_file: dest=/etc/clues2/conf.d/plugin-slurm.cfg section=SLURM option=SLURM_NODES_COMMAND value="{{item}} -o show nodes"
  with_first_found:
   - /usr/bin/scontrol
   - /usr/local/bin/scontrol
  notify: restart cluesd
- ini_file: dest=/etc/clues2/conf.d/plugin-slurm.cfg section=SLURM option=SLURM_JOBS_COMMAND value="{{item}} -o show jobs"
  with_first_found:
   - /usr/bin/scontrol
   - /usr/local/bin/scontrol
  notify: restart cluesd

- copy: src={{ item }} dest=/usr/local/bin/sbatch.o mode=755 force=no
  with_first_found:
   - /usr/bin/sbatch
   - /usr/local/bin/sbatch

- copy: src=/usr/local/bin/clues-slurm-wrapper dest={{ item }} force=no
  with_first_found:
   - /usr/bin/sbatch
   - /usr/local/bin/sbatch
  when: ansible_os_family == "Debian"
- copy: src=/usr/bin/clues-slurm-wrapper dest={{ item }} force=no
  with_first_found:
   - /usr/bin/sbatch
   - /usr/local/bin/sbatch
  when: ansible_os_family == "RedHat"
